---
collections:
  - name: awx.awx
    version: 11.2.0

  - name: check_point.mgmt
    version: 2.0.0

  - name: azure.azcollection
    version: 1.13.0

  - name: chocolatey.chocolatey
    version: 1.2.0

  - name: ansible.windows
    version: 1.9.0

  - name: community.windows
    version: 1.9.0
