---
- name: "Install the required Windows packages"
  chocolatey.chocolatey.win_chocolatey:
    name: '{{ item }}'
    state: present
  loop:
    - vcredist2010
    - vcredist2012
    - vcredist2017
    - putty.install

- name: "Copy SmartConsole Install Script to Win10 VM"
  ansible.windows.win_copy:
    src: files/install.ps1
    dest: 'c:\\Users\\azureuser\\Desktop\\install_smartconsole.ps1'
    force: no

- name: "Download Checkpoint SmartConsole into Win10 VM"
  ansible.windows.win_get_url:
    url: "{{ win10_blob }}"
    dest: 'C:\Users\azureuser\Desktop\SmartConsole.exe'

- name: "Installing CheckPoint SmartConsole with the PS1 Script in Win10 VM"
  ansible.windows.win_powershell:
    script: |
      C:\\Users\\azureuser\\Desktop\\SmartConsole.exe -s
    executable: powershell.exe

#- name: "Installing CheckPoint SmartConsole with the PS1 Script in Win10 VM"
#  community.windows.psexec:
#    # hostname: '{{ hostvars[inventory_hostname]["ansible_host"] | default(inventory_hostname) }}'
#    hostname: w10
#    connection_username: "{{ ansible_user }}"
#    connection_password: "{{ ansible_password }}"
#    encrypt: no
#    integrity_level: elevated
#    process_username: "{{ ansible_user }}"
#    process_password: "{{ ansible_password }}"
#    executable: C:\Users\azureuser\Desktop\SmartConsole.exe
#    arguments: '-s'
#  delegate_to: localhost

#- name: "Installing CheckPoint SmartConsole with the PS1 Script in Win10 VM"
#  ansible.windows.win_shell: 'C:\\Users\\azureuser\\Desktop\\install_smartconsole.ps1'
