---

- name: Install the Visual C++ Redistributable 2010
  win_package:
    path: https://ansiblefest2020blob.blob.core.windows.net/ansiblefest2020/vcredist_2010_x86.exe
    product_id: '{196BB40D-1578-3D01-B289-BEFC77A11A1E}'
    arguments: /install /passive /norestart

- name: Install the Visual C++ Redistributable 2012
  win_package:
    path: https://ansiblefest2020blob.blob.core.windows.net/ansiblefest2020/vcredist_2011_x86.exe
    product_id: '{33d1fd90-4274-48a1-9bc1-97e33d9c2d6f}'
    arguments: /install /passive /norestart

- name: Install the Visual C++ Redistributable 2017
  win_package:
    path: https://ansiblefest2020blob.blob.core.windows.net/ansiblefest2020/vcredist_2017_x86.exe
    product_id: '{67f67547-9693-4937-aa13-56e296bd40f6}'
    arguments: /install /passive /norestart

- name: Copy SmartConsole Install Script
  win_copy:
    src: files/install.ps1
    dest: 'c:\\Users\\azureuser\\Desktop\\install_smartconsole.ps1'
    force: no

- name: Copy Putty
  win_copy:
    src: files/putty.exe
    dest: 'c:\Users\azureuser\Desktop\putty.exe'
    force: no

- name: Download Checkpoint SmartConsole
  win_get_url:
    url: "{{ win10_blob }}"
    dest: 'C:\Users\azureuser\Desktop\SmartConsole.exe'

- win_shell: 'C:\\Users\\azureuser\\Desktop\\install_smartconsole.ps1'
  become: yes
  become_user: azureuser
