---
- name: "Install the required Windows packages"
  chocolatey.chocolatey.win_chocolatey:
    name: '{{ item }}'
    state: present
  loop:
    - vcredist2010
    - vcredist2012
    - vcredist2017
    - putty.install

- name: "Create Checkpoint SmartConsole directory"
  ansible.windows.win_file:
    path: 'C:\Program Files (x86)\CheckPoint'
    state: directory

- name: "Download Checkpoint SmartConsole zip into Win10 VM"
  ansible.windows.win_get_url:
    url: "{{ win10_blob }}"
    dest: 'C:\Program Files (x86)\CheckPoint'

- name: "Decompress Checkpoint SmartConsole zip"
  community.windows.win_unzip:
    src: 'C:\Program Files (x86)\CheckPoint\Check_Point_SmartConsole_R81_10_jumbo_HF_B409_Win_portable.zip'
    dest: 'C:\Program Files (x86)\CheckPoint'
    delete_archive: yes

- name: "Create Checkpoint SmartConsole shortcut on the desktop"
  community.windows.win_shortcut:
    src: 'C:\Program Files (x86)\CheckPoint\SmartConsole.exe'
    dest: 'C:\Users\azureuser\Desktop\SmartConsole.lnk'
