---

- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vault/vault.yml
    - vars/common.yml
    - "vars/{{ lab_name }}.yml"
  roles:
    - azure/create-tower

- hosts: ansible-tower
  vars_files:
    - vars/vars-tower.yml
    - vault/vault.yml
  vars:
    ansible_ssh_user: azureuser
    ansible_ssh_pass: "{{ password }}"
    ansible_become_pass: "{{ password }}"
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
  roles:
  - role: tower/config-ansible-tower
  - role: tower/config-ansible-tower-license
#  tags:
#  - 'never'
#  - 'install'

- hosts: ansible-tower
  become: yes
  vars:
    ansible_ssh_user: azureuser
    ansible_ssh_pass: "{{ password }}"
    ansible_become_pass: "{{ password }}"
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
  vars_files:
    - vars/vars-tower.yml
    - vault/vault.yml
  roles:
  - role: tower/config-ansible-tower-package
#  tags:
#  - 'install'

- hosts: ansible-tower
  vars_files:
    - vars/vars-tower.yml
    - vault/vault.yml
  vars:
    ansible_ssh_user: azureuser
    ansible_ssh_pass: "{{ password }}"
    ansible_become_pass: "{{ password }}"
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
  roles:
  - role: tower/manage-credentials
  - role: tower/manage-inventories
  - role: tower/manage-projects
  - role: tower/manage-job-templates
#  tags:
#  - 'always'
