---
# tasks file for rhel/deploy-ticketapp/

- name: Copy ticket-monster application WAR to host
  ansible.builtin.copy:
    src: ticket-monster.war
    dest: /tmp/ticket-monster.war
    mode: '0644'

- name: Deploy ticket-monster application WAR to host
  community.general.jboss:
    src: /tmp/ticket-monster.war
    deploy_path: /opt/rh/eap7/root/usr/share/wildfly/standalone/deployments
    deployment: ticket-monster.war
    state: present
