---
# tasks file for rhel/deploy-ticketapp/

- name: Deploy ticket-monster application WAR to host
  ansible.builtin.copy:
    src: ticket-monster.war
    dest: /opt/rh/eap7/root/usr/share/wildfly/standalone/deployments/

#- name: "Unzip WAR file"
#  unarchive:
#    src: "/tmp/ticket-monster.war"
#    dest: "/usr/share/tomcat/webapps/ROOT/"
#    copy: no
#    mode: 0755
#    owner: tomcat
#    group: tomcat
#  notify: restart tomcat

#- name: "Not use firewalld"
#  service:
#    name: firewalld
#    state: stopped
#    enabled: False
