---
## NOTE: This automation code is originally developed, tested and provided by Diego Escobar (@dearevalillo) from CheckPoint
##       Many thanks to Diego for provide and test this code!

# Task to add simple gateway object in Check Point management server
- name: Add, set or delete simple-gateway
  check_point.mgmt.cp_mgmt_simple_gateway:
    state: present
    name: "{{ gw_resgroup }}"
    comments: "{{ simple_gw_comments }}"
    anti_bot: "{{ simple_gw_anti_bot }}"
    anti_virus: "{{ simple_gw_anti_virus }}"
    application_control: "{{ simple_gw_appi_ctrl }}"
    color: "{{ simple_gw_color }}"
    firewall: "{{ simple_gw_firewall }}"
    ips: "{{ simple_gw_ips }}"
    ipv4_address: "{{ simple_gw_eth0_ipv4 }}"
    one_time_password: "{{ simple_gw_sickey }}"
    threat_emulation: "{{ simple_gw_threat_emulation }}"
    url_filtering: "{{ simple_gw_url_filtering }}"
    gateway_version: "{{ simple_gw_gw_version }}"
    interfaces:
      - name: eth0
        color: "{{ simple_gw_eth0_color}}"
        comments: "{{ simple_gw_eth0_comments }}"
        ipv4_address: "{{ simple_gw_eth0_ipv4 }}"
        ipv4_network_mask: "{{ simple_gw_eth0_ipv4_network_mask }}"
        anti_spoofing: "{{ simple_gw_eth0_anti_spoofing }}"
        topology: "{{ simple_gw_eth0_topology }}"
        security_zone: "{{ simple_gw_eth0_security_zone }}"
        security_zone_settings:
          specific_zone: "{{ simple_gw_eth0_specific_zone }}"
      - name: eth1
        color: "{{ simple_gw_eth1_color }}"
        comments: "{{ simple_gw_eth1_comments }}"
        ipv4_address: "{{ simple_gw_eth1_ipv4 }}"
        ipv4_network_mask: "{{ simple_gw_eth1_ipv4_network_mask }}"
        anti_spoofing: "{{ simple_gw_eth1_anti_spoofing }}"
        topology: "{{ simple_gw_eth1_topology }}"
        topology_settings:
          ip_address_behind_this_interface: "{{ simple_gw_eth1_topology_ip_behind_if }}"
          interface_leads_to_dmz: true
        security_zone: "{{ simple_gw_eth1_security_zone }}"
        security_zone_settings:
          specific_zone: "{{ simple_gw_eth1_specific_zone }}"
    auto_publish_session: true
  no_log: false
