---

# Manually Done. Use the new modules for deploy the simple GW

## NOTE: This automation code is originally developed, tested and provided by Diego Escobar (@dearevalillo) from CheckPoint
##       Many thanks to Diego for provide and test this code!

# - name: Add, set or delete simple-gateway
#   check_point.mgmt.cp_mgmt_simple_gateway:
#     state: "{{item.state}}"
#     name: "{{item.name}}"
#     comments: "{{item.comments}}" 
#     anti_bot: "{{item.anti_bot}}"
#     anti_virus: "{{item.anti_virus}}"
#     application_control: "{{item.appi_ctrl}}"
#     color: "{{item.color}}"
#     firewall: "{{item.firewall}}"
#     ips: "{{item.ips}}"
#     ipv4_address: "{{item.eth0_ipv4}}" 
#     one_time_password: "{{item.sickey}}"
#     threat_emulation: "{{item.threat_emulation}}"
#     url_filtering: "{{item.url_filtering}}"
#     gateway_version: "{{item.gw_version}}"
#     interfaces:
#     - name: eth0
#       color: "{{item.eth0_color}}"
#       comments: "{{item.eth0_comments}}"
#       ipv4_address: "{{item.eth0_ipv4}}" 
#       ipv4_network_mask: "{{item.eth0_ipv4_network_mask}}"
#       anti_spoofing: "{{item.eth0_anti_spoofing}}" 
#       topology: "{{item.eth0_topology}}"
#       security_zone: "{{item.eth0_security_zone}}"
#       security_zone_settings:
#         specific_zone: "{{item.eth0_specific_zone}}"      
#     - name: eth1
#       color: "{{item.eth1_color}}"
#       comments: "{{item.eth1_comments}}"
#       ipv4_address: "{{item.eth1_ipv4}}" 
#       ipv4_network_mask: "{{item.eth1_ipv4_network_mask}}"
#       anti_spoofing: "{{item.eth1_anti_spoofing}}"
#       topology: "{{item.eth1_topology}}"
#       topology_settings:
#         ip_address_behind_this_interface: "{{item.eth1_topology_ip_behind_if}}"
#         interface_leads_to_dmz: true
#       security_zone: "{{item.eth1_security_zone}}"
#       security_zone_settings:
#         specific_zone: "{{item.eth1_specific_zone}}"
#     auto_publish_session: true
#   no_log: true
#   loop: "{{cp_mgmt_simple_gateway_vars}}"