---
# tasks file for rhel/install-jboss/

- name: "Install Java 1.8"
  yum:
    name: java-1.8.0-openjdk
    state: present

- name: "Add group jboss"
  group:
    name: tomcat

- name: "Add user jboss"
  user:
    name: "tomcat"
    group: "tomcat"
    home: "/usr/share/tomcat"
    createhome: no
  become: True
  become_method: sudo

- name: "Download JBOSS standalone"
  get_url:
    url: "http://archive.apache.org/dist/tomcat/tomcat-9/v9.0.24/bin/apache-tomcat-9.0.24.tar.gz"
    dest: "/opt/apache-tomcat-9.0.24.tar.gz"

- name: "Extract archive"
  command: chdir=/usr/share /bin/tar xvf /opt/apache-tomcat-9.0.24.tar.gz -C /opt/ creates=/opt/apache-tomcat-9.0.24

- name: "Symlink install directory"
  file:
    src: "/opt/apache-tomcat-9.0.24"
    path: "/usr/share/tomcat"
    state: link

- name: "Change ownership of JBOSS installation"
  file:
    path: "/usr/share/tomcat/"
    owner: tomcat
    group: tomcat
    state: directory
    recurse: yes

- name: "Configure JBOSS server"
  template:
    src: "server.xml"
    dest: "/usr/share/tomcat/conf/"
  notify: restart tomcat

- name: "Configure JBOSS users"
  template:
    src: "tomcat-users.xml"
    dest: "/usr/share/tomcat/conf/"
  notify: restart tomcat

- name: "Install JBOSS init script"
  copy:
    src: "tomcat-initscript.sh"
    dest: "/etc/init.d/tomcat"
    mode: 0755

- name: "Start JBOSS"
  service:
    name: tomcat
    state: started
    enabled: yes

- name: "Wait for JBOSS to start"
  wait_for:
    port: "{{http_port}}"

