---
# tasks file for rhel/install-jboss/

- name: Subscribe and auto-subscribe to available content
  community.general.redhat_subscription:
    state: present
    username: "{{ rht_subs_username }}"
    password: "{{ rht_subs_password }}"
    auto_attach: true

- name: Enable a JBoss EAP repository
  community.general.rhsm_repository:
    name: jb-eap-7.4-for-rhel-8-x86_64-rpms
    state: enabled

- name: Install JBoss EAP and JDK 11
  ansible.builtin.dnf:
    name:
      - '@jboss-eap7-jdk11'
    state: latest

- name: Correct Java version selected
  community.general.alternatives:
    name: java
    path: /usr/lib/jvm/java-11-openjdk-11.0.16.1.1-1.el8_6.x86_64/bin/java

- name: Template JBoss EAP standalone configuration
  ansible.builtin.template:
    src: standalone.xml.j2
    dest: /opt/rh/eap7/root/usr/share/wildfly/standalone/configuration/standalone.xml
    owner: jboss
    group: jboss
    mode: '0664'

- name: Enable service JBoss EAP standalone and ensure it is not masked
  ansible.builtin.systemd:
    name: eap7-standalone
    state: started
    enabled: yes
    masked: no

- name: Stop service Firewalld and ensure it is masked
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: no
    masked: yes
