---

# Manually done with the guide
# https://supportcenter.checkpoint.com/supportcenter/portal?eventSubmit_doGoviewsolutiondetails=&solutionid=sk92449

- name: "Waiting for SSH connection to SMS become available"
  wait_for:
    port: 22
    host: '{{ ansible_host }}'
    search_regex: OpenSSH
    delay: 10
  connection: local
