---
# Manually done with the guide
# https://supportcenter.checkpoint.com/supportcenter/portal?eventSubmit_doGoviewsolutiondetails=&solutionid=sk92449

## NOTE: This automation code is originally developed, tested and provided by Diego Escobar (@dearevalillo) from CheckPoint
##       Many thanks to Diego for provide and test this code!

- name: "Wait Agent update finished"
  command: >
    clish -c 'show installer status'
  register: agent_install
  retries: 10
  delay: 5
  until: agent_install.stdout.find("agent build is up to date") != -1

- name: "Download JHF T66"
  command: >
    bash -lc "clish -c 'installer download Check_Point_R81_10_JUMBO_HF_MAIN_Bundle_T66_FULL.tgz not-interactive'"
  register: jhf_downloaded
  retries: 40
  delay: 10
  until: jhf_downloaded.stdout.find("Available for Install") != -1

- name: "Verify Jumbo Hotfix package via Agent"
  command: >
    bash -lc "clish -c 'installer verify Check_Point_R81_10_JUMBO_HF_MAIN_Bundle_T66_FULL.tgz'"
  register: jhf_verify
  retries: 30
  delay: 10
  until: jhf_verify.stdout.find("Package is available for installation") != -1

- name: "Install Jumbo Hotfix via Agent"
  command: >
    bash -lc "clish -c 'installer install Check_Point_R81_10_JUMBO_HF_MAIN_Bundle_T66_FULL.tgz not-interactive'"

- name: "Checking Jumbo Hotfix installation is Installed"
  command: >
    bash -lc "clish -c 'show installer package Check_Point_R81_10_JUMBO_HF_MAIN_Bundle_T66_FULL.tgz status'"
  register: jhf_status
  retries: 150
  delay: 5
  until: jhf_status.stdout.find("Installed") != -1

- name: "SMS Rebooting"
  debug:
    msg: "Checkpoint SMS Rebooting..."

- name: "Waiting for connection to SMS become reachable"
  wait_for_connection:
    connect_timeout: 60
    timeout: 360
    delay: 60

- name: "Waiting for SSH connection to SMS become available"
  wait_for:
    port: 22
    host: "{{ ansible_host }}"
    search_regex: OpenSSH
    delay: 10
  connection: local
