---

- name: "Destroy Checkpoint SMS"
  azure_rm_resourcegroup:
    name: "{{ item }}"
    location: "{{ location }}"
    state: absent
    force_delete_nonempty: yes
  loop:
    - "{{ sms_resgroup }}"

- name: "Pause a bit"
  pause:
    seconds: 40
