---

- name: "Destroy Checkpoint SMS"
  azure_rm_resourcegroup:
    name: "{{ item }}"
    location: "{{ location }}"
    state: absent
    force_delete_nonempty: yes
  loop:
    - "{{ sms_resgroup }}"

- name: "Pause a bit"
  pause:
    seconds: 40

# - name: "Create Checkpoint GW"
#   azure_rm_resourcegroup:
#     name: "{{ item }}"
#     location: "{{ location }}"
#     state: absent
#     force_delete_nonempty: yes
#   loop:
#     - "{{ gw_resgroup }}"

