---

- hosts: rhel2
  become: yes
  vars_files:
    - vault/vault.yml
    - vars/common.yml
    - "vars/{{ lab_name }}.yml"
  tasks:
    - name: '[ANSIBLEFEST22] Install Microshift in RHEl2'
      include_role:
        name: "rhel/install-microshift"
