---

- hosts: rhel1
  become: yes
  vars_files:
    - vars/common.yml
    - vault/vault.yml
    - "vars/{{ lab_name }}.yml"
  tasks:
    - name: '[ANSIBLEFEST] Install Jboss in RHEL1'
      include_role:
        name: "rhel/install-jboss"
