---

- hosts: ckp-gw
  vars_files:
    - vault/vault.yml
    - vars/common.yml
    - "vars/{{ lab_name }}.yml"
  gather_facts: False
  tasks:
    - name: '[ANSIBLEFEST22] Config Add Simple GW to Checkpoint'
      include_role:
        name: "ckp/add-route-subnet-dmz-gw"
