---

- hosts: ckp-sms
  gather_facts: False
  connection: httpapi
  vars_files:
    - vault/vault.yml
    - vars/common.yml
    - "vars/{{ lab_name }}.yml"
  tasks:
    - name: '[ANSIBLEFEST22] Deploy Security hosts into Checkpoint sms'
      include_role:
        name: "ckp/deploy-sec-hosts"
