---

- hosts: rhel
  vars_files:
    - vault/vault.yml
    - vars/common.yml
    - "vars/{{ lab_name }}.yml"
  tasks:
    - name: '[ANSIBLEFEST] Install SmartConsole in Win10'
      include_role:
        name: "rhel/config-rhel"
