---

- hosts: ckpsms
  gather_facts: False
  connection: httpapi
  vars_files:
    - vault/vault.yml
    - vars/common.yml
    - "vars/{{ lab_name }}.yml"
  tasks:
    - name: '[ANSIBLEFEST] Deploy Security hosts into Checkpoint sms'
      include_role:
        name: "ckp/deploy-sec-hosts"
