---

- hosts: localhost
  connection: local
  vars_files:
    - vars/common.yml
    - vault/vault.yml
    - "vars/{{ lab_name }}.yml"
  tasks:
    - name: '[ANSIBLEFEST22] Deploy RHEL instances in Azure'
      include_role:
        name: "azure/create-rhel"
