---

- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vault/vault.yml
    - vars/common.yml
    - "vars/{{ lab_name }}.yml"
  roles:
    - azure/create-tower
  tasks:
    - name: '[ANSIBLEFEST22] Create Tower VM in Azure'
      include_role:
        name: "azure/pre-azure-infra"