---

- name: "Deploy Infra Azure"
  hosts: localhost
  connection: local
  vars_files:
    - vault/vault.yml
    - vars/common.yml
    - "vars/{{ lab_name }}.yml"
  tasks:
    - name: '[ANSIBLEFEST] Deploy the Azure Net Infrastructure'
      include_role:
        name: "azure/pre-azure-infra"

- name: "Create Tower VM"
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vault/vault.yml
    - vars/common.yml
    - "vars/{{ lab_name }}.yml"
  roles:
    - azure/create-tower

- name: "Deploy Ansible Tower"
  hosts: ansible-tower
  become: true
  gather_facts: no
  vars_files:
    - vars/vars-tower.yml
    - vault/vault.yml
    - common.yml
  vars:
    ansible_ssh_user: azureuser
    ansible_ssh_pass: "{{ password }}"
    ansible_become_pass: "{{ password }}"
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
  roles:
    - redhat_cop.aap_utilities.aap_setup_download
    - redhat_cop.aap_utilities.aap_setup_prepare
    - redhat_cop.aap_utilities.aap_setup_install

- name: "Post Configuration of Ansible Tower"
  hosts: ansible-tower
  vars_files:
    - vars/vars-tower.yml
    - vault/vault.yml
    - "vars/{{ lab_name }}.yml"
  vars:
    ansible_ssh_user: azureuser
    ansible_ssh_pass: "{{ password }}"
    ansible_become_pass: "{{ password }}"
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
  roles:
  - role: tower/manage-credentials
  - role: tower/manage-projects
  - role: tower/manage-inventories
#  tags:
#  - 'always'

- name: "Pause a bit"
  hosts: ansible-tower
  vars_files:
    - vars/vars-tower.yml
    - vault/vault.yml
    - "vars/{{ lab_name }}.yml"
  vars:
    ansible_ssh_user: azureuser
    ansible_ssh_pass: "{{ password }}"
    ansible_become_pass: "{{ password }}"
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
  tasks:
    - name: "pause a bit"
      pause:
        seconds: 30

- name: "Post Configuration of Ansible Tower"
  hosts: ansible-tower
  vars_files:
    - vars/vars-tower.yml
    - vault/vault.yml
    - "vars/{{ lab_name }}.yml"
  vars:
    ansible_ssh_user: azureuser
    ansible_ssh_pass: "{{ password }}"
    ansible_become_pass: "{{ password }}"
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
  roles:
  - role: tower/manage-job-templates
