---

- hosts: localhost
  connection: local
  vars_files:
    - vault/vault.yml
    - vars/common.yml
    - "vars/{{ lab_name }}.yml"
  tasks:
    - name: '[ANSIBLEFEST22] Deploy the Azure Net Infrastructure'
      include_role:
        name: "azure/pre-azure-infra"